server:
  adminConnectors:
  - type: http
    port: 9091
  applicationConnectors:
  - type: http
    port: 9090
logging:
  level: INFO
  loggers:
    com.newcontext.etl: TRACE
  appenders:
  - type: console
    logFormat: '[%d{HH:mm:ss.SSS}][%-5level][%logger{5}][%mdc]: %msg%n'
dataSourceName: ${DATASOURCE_NAME}
databaseName: ${DATABASE_NAME}
dataSourceUser: ${DATASOURCE_USER}
dataSourcePassword: ${DATASOURCE_PASSWORD}
uploadTargetName: ${UPLOAD_TARGET_NAME}
catFavoritePlace: ${CAT_FAVORITE_PLACE}